---
# tasks file for deploying monitoring tools

- name: Install monitoring dependencies
  apt:
    pkg:
      - perl
      - libnet-ldap-perl
      - monitoring-plugins-contrib

- name: extract Nagios archive
  ansible.builtin.unarchive:
    src: "{{ ltb_base_url }}/{{ ltb_nagios_archive_name }}"
    dest: "{{ ltb_nagios_dest_path }}"
    remote_src: yes
    extra_opts: "{{ ltb_nagios_unarchive_opts }}"

- name: extract Cacti archive
  ansible.builtin.unarchive:
    src: "{{ ltb_base_url }}/{{ ltb_cacti_archive_name }}"
    dest: "{{ ltb_cacti_dest_path }}"
    remote_src: yes
    extra_opts: "{{ ltb_cacti_unarchive_opts }}"
