name: Test ansible-role-ldaptoolbox-openldap

on: push

jobs:
  test-deployment:
    runs-on: ubuntu-latest
    name: test ansible-role-ldaptoolbox-openldap syntax
    steps:
      - uses: actions/checkout@v2
      - name: test ansible check
      - run: |
          git fetch --unshallow
          git pull origin
          git config user.email "automatic@github.com"
          git config user.name "GitHub Actions"
        run: |
          sudo apt-get install -y python3-pip
          sudo pip install ansible
          ansible --version
          printf '[defaults]\nroles_path=../' >ansible.cfg
          ansible-playbook tests/test.yml -i tests/inventory --syntax-check
