name: Test ansible deployment

on: push

jobs:
  test-deployment:
    runs-on: ubuntu-latest
    name: Test ansible deployment
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --unshallow
          git pull origin
          git config user.email "automatic@github.com"
          git config user.name "GitHub Actions"
      - name: test ansible
        run: |
          ansible-playbook tests/test.yml -i tests/inventory --syntax-check
